language: php
php:
  - 7.2
  - 7.3
  - 7.4
sudo: false
# download test suite and run tests... submodule? meta testing project with
# all of the reference implementations?
script: 
  - git clone https://github.com/json-ld/json-ld.org.git _json-ld.org
  - phpunit --group json-ld.org test.php -d ./_json-ld.org/test-suite
  #- git clone https://github.com/json-ld/normalization.git _normalization
  #- phpunit --group normalization test.php -d ./_normalization/tests
notifications:
  email:
    on_success: change
    on_failure: change
